// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckNpcap() {
  return window['go']['main']['App']['CheckNpcap']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CreateDb(arg1) {
  return window['go']['main']['App']['CreateDb'](arg1);
}

export function CreateTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3, arg4);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DeleteTaskReport(arg1) {
  return window['go']['main']['App']['DeleteTaskReport'](arg1);
}

export function DisableGetBattleReport() {
  return window['go']['main']['App']['DisableGetBattleReport']();
}

export function EnableGetBattleReport() {
  return window['go']['main']['App']['EnableGetBattleReport']();
}

export function EnableGetReport(arg1) {
  return window['go']['main']['App']['EnableGetReport'](arg1);
}

export function GetDbList() {
  return window['go']['main']['App']['GetDbList']();
}

export function GetGroupWu() {
  return window['go']['main']['App']['GetGroupWu']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetPlayerTeam(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPlayerTeam'](arg1, arg2, arg3);
}

export function GetReportNumByTaskId(arg1) {
  return window['go']['main']['App']['GetReportNumByTaskId'](arg1);
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function GetTaskList() {
  return window['go']['main']['App']['GetTaskList']();
}

export function GetTeamGroup() {
  return window['go']['main']['App']['GetTeamGroup']();
}

export function GetTeamUser() {
  return window['go']['main']['App']['GetTeamUser']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SelectDb(arg1) {
  return window['go']['main']['App']['SelectDb'](arg1);
}

export function StatisticsReport(arg1) {
  return window['go']['main']['App']['StatisticsReport'](arg1);
}
